### ISSUE TITLE
@ in path seems to confuse parser

### ISSUE THREAD

**Issue by oliversalzburg** [xpl/stacktracey#6]
![image](https://user-images.githubusercontent.com/1658949/78135121-a0476e00-7421-11ea-88db-93ea40258dd2.png)

The individual elements seem to be improperly split on the `@`, leading to incomplete elements.

**Comment by xpl** [comment]
@oliversalzburg I just fixed it. Let me know if something still isn't right.

**Comment by oliversalzburg** [comment]
Looks pretty good!

btw, is there a way to combine the effects of `.clean` and `.pretty`? To not have the third-party call sites in the pretty-printed output?

**Comment by xpl** [comment]
@oliversalzburg Hmm, try`.clean.pretty`? It must've been non-obvious from the documentation, sorry about that — I've just fixed it too!

**Comment by oliversalzburg** [comment]
Oh that's nice! I was confused by the VS Code Intellisense, which didn't show `.clean.pretty` as an option and it was also not shown specifically in the documentation. That was enough for me to not try it out anyway. Thanks for the heads-up, looks great :)
