### ISSUE TITLE
Typescript Definitions 

### ISSUE THREAD

**Issue by kishanio** [xpl/stacktracey#7]
I'mma have sometime next weekend if incase need help with this?

**Comment by xpl** [comment]
@kishanio JFYI I have finally added the definitions. Feel free to edit it in case I missed something.

https://github.com/xpl/stacktracey/blob/master/stacktracey.d.ts

There also have been some breaking changes in the API, see the changelog for a brief description: https://github.com/xpl/stacktracey/blob/master/CHANGELOG.md#version-20-with-breaking-changes

The version number has been bumped to 2.0
