### ISSUE TITLE
StackTracey.filter not correctly defined

### ISSUE THREAD

**Issue by josesan9** [xpl/stacktracey#9]
Hi,

in the example code, this line of code is provided:
```
s = new StackTracey().slice(1).filter(x => !x.thirdParty)
```
Where the filter function returns a boolean. In the StackTracey.d.ts definition file, the definition for this is stated as follows:
```
filter (f: (x: Entry, i: number, arr: Entry[]) => Entry): StackTracey
```
This is asking for an Entry to be returned instead of a boolean. Is this correct? or is the typescript definition file wrong?

**Comment by xpl** [comment]
Hi, that was a copypasta error. Thanks for spotting it.
